version: '3.8'
services:
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: hr_schema
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234